### ISSUE TITLE
Error:Could not get unknown property 'assembleDebug' for project ':photofilterssdk' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by Jaymin-Bhadani** [Zomato/AndroidPhotoFilters#12]

**Comment by RockyLin** [comment]
Same problem here.

**Comment by sachinmutthe** [comment]
Hello Guys,

I **resolved** that issue by following steps. Hope will be helpfull for others.

**Step 1:** To find the line, put your project in "Project" mod in Android Studio

**Step 2:** Right click on the Root folder, find in path, type "assembleDebug". It is in the quality.gradle for me

**Step 3:** Replace assembleDebug with "assembleDebug" (Actually, we just need to put double quotes to assembleDebug keyword because of gradle version 2.2.0.) and rebuild the project. 

**Enjoy.
Sachin.**

**Comment by shubhamchaudhary** [comment]
Great, Thanks Sachin, marking this as closed for now.
